using Godot;
using System.Collections.Generic;

public sealed class MonsterLootDefinition
{
	public int UniqueId { get; set; }
	public string Id { get; set; } = string.Empty;
	public string NameKey { get; set; } = string.Empty;
	public Color DropColor { get; set; }
}

public static class MonsterLootCatalog
{
	private static readonly MonsterLootDefinition[] LegacyQuestMaterialDefaults =
	{
		new() { Id = "loot.slime_mucus", NameKey = "item.loot.slime_mucus", DropColor = new Color(0.32f, 0.92f, 0.78f, 0.95f) },
		new() { Id = "loot.beast_hide", NameKey = "item.loot.beast_hide", DropColor = new Color(0.62f, 0.38f, 0.22f, 0.95f) },
		new() { Id = "loot.sharp_claw", NameKey = "item.loot.sharp_claw", DropColor = new Color(0.92f, 0.86f, 0.64f, 0.95f) },
		new() { Id = "loot.soft_fur", NameKey = "item.loot.soft_fur", DropColor = new Color(0.82f, 0.70f, 0.58f, 0.95f) },
		new() { Id = "loot.small_bone", NameKey = "item.loot.small_bone", DropColor = new Color(0.86f, 0.82f, 0.72f, 0.95f) },
		new() { Id = "loot.insect_wing", NameKey = "item.loot.insect_wing", DropColor = new Color(0.72f, 0.92f, 0.76f, 0.95f) },
		new() { Id = "loot.red_horn", NameKey = "item.loot.red_horn", DropColor = new Color(0.88f, 0.22f, 0.14f, 0.95f) },
		new() { Id = "loot.venom_sac", NameKey = "item.loot.venom_sac", DropColor = new Color(0.54f, 0.88f, 0.22f, 0.95f) },
		new() { Id = "loot.water_core", NameKey = "item.loot.water_core", DropColor = new Color(0.34f, 0.72f, 1.0f, 0.95f) },
		new() { Id = "loot.dragon_scale", NameKey = "item.loot.dragon_scale", DropColor = new Color(0.86f, 0.34f, 0.18f, 0.95f) },
		new() { Id = "loot.cracked_core", NameKey = "item.loot.cracked_core", DropColor = new Color(0.70f, 0.68f, 0.62f, 0.95f) },

		// 強化水晶 T1~T10：所有怪物依其世界階級（WorldTier）掉落，作為精煉裝備的材料。
		new() { Id = "loot.enhance_crystal.t1", NameKey = "item.loot.enhance_crystal.t1", DropColor = new Color(0.70f, 0.74f, 0.80f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t2", NameKey = "item.loot.enhance_crystal.t2", DropColor = new Color(0.56f, 0.82f, 0.72f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t3", NameKey = "item.loot.enhance_crystal.t3", DropColor = new Color(0.42f, 0.84f, 0.58f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t4", NameKey = "item.loot.enhance_crystal.t4", DropColor = new Color(0.50f, 0.80f, 1.00f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t5", NameKey = "item.loot.enhance_crystal.t5", DropColor = new Color(0.36f, 0.62f, 1.00f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t6", NameKey = "item.loot.enhance_crystal.t6", DropColor = new Color(0.62f, 0.48f, 1.00f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t7", NameKey = "item.loot.enhance_crystal.t7", DropColor = new Color(0.82f, 0.42f, 0.98f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t8", NameKey = "item.loot.enhance_crystal.t8", DropColor = new Color(1.00f, 0.44f, 0.72f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t9", NameKey = "item.loot.enhance_crystal.t9", DropColor = new Color(1.00f, 0.58f, 0.30f, 0.96f) },
		new() { Id = "loot.enhance_crystal.t10", NameKey = "item.loot.enhance_crystal.t10", DropColor = new Color(1.00f, 0.86f, 0.36f, 0.98f) },
	};
	private static readonly MonsterLootDefinition[] QuestMaterials = ItemCatalogLoader.LoadMaterials();

	private static readonly string[] EnhanceCrystalIds =
	{
		"loot.enhance_crystal.t1", "loot.enhance_crystal.t2", "loot.enhance_crystal.t3",
		"loot.enhance_crystal.t4", "loot.enhance_crystal.t5", "loot.enhance_crystal.t6",
		"loot.enhance_crystal.t7", "loot.enhance_crystal.t8", "loot.enhance_crystal.t9",
		"loot.enhance_crystal.t10",
	};

	// 對應世界階級 / 精煉目標星等的水晶 id（tier 1~10）。
	public static string GetEnhanceCrystalId(int tier)
	{
		return EnhanceCrystalIds[Mathf.Clamp(tier, 1, EnhanceCrystalIds.Length) - 1];
	}

	public static bool IsEnhanceCrystal(string itemId)
	{
		return !string.IsNullOrEmpty(itemId) && itemId.StartsWith("loot.enhance_crystal.t", System.StringComparison.Ordinal);
	}

	public static int GetEnhanceCrystalTier(string itemId)
	{
		if (!IsEnhanceCrystal(itemId))
		{
			return 0;
		}

		string suffix = itemId.Substring("loot.enhance_crystal.t".Length);
		return int.TryParse(suffix, out int tier) ? Mathf.Clamp(tier, 1, EnhanceCrystalIds.Length) : 0;
	}

	// Core orbs are a combinatorial material family (element x tier) produced by
	// dismantling pets and consumed by the core-enhancement merchant. They are
	// generated by codec rather than authored as ~90 JSON rows; inventory
	// persists them by string id so no uniqueId registration is needed.
	public const string UniversalOrbElement = "universal";
	private const string CoreOrbPrefix = "loot.core_orb.";

	private static readonly Dictionary<string, Color> CoreOrbColors = new()
	{
		{ "fire", new Color(1.0f, 0.45f, 0.25f, 0.96f) },
		{ "water", new Color(0.35f, 0.6f, 1.0f, 0.96f) },
		{ "lightning", new Color(0.95f, 0.9f, 0.35f, 0.96f) },
		{ "ice", new Color(0.6f, 0.9f, 1.0f, 0.96f) },
		{ "poison", new Color(0.6f, 0.9f, 0.35f, 0.96f) },
		{ "wind", new Color(0.6f, 1.0f, 0.8f, 0.96f) },
		{ "dark", new Color(0.55f, 0.4f, 0.75f, 0.96f) },
		{ "light", new Color(1.0f, 0.95f, 0.7f, 0.96f) },
		{ UniversalOrbElement, new Color(0.85f, 0.85f, 0.9f, 0.96f) },
	};

	// Builds the orb id for an element (empty/"physical" -> universal) and tier.
	public static string GetCoreOrbId(string element, int tier)
	{
		string el = string.IsNullOrEmpty(element) || element == "physical" ? UniversalOrbElement : element;
		return $"{CoreOrbPrefix}{el}.t{Mathf.Clamp(tier, 1, CoreEnhanceConfig.MaxOrbTier)}";
	}

	public static bool IsCoreOrb(string itemId)
	{
		return !string.IsNullOrEmpty(itemId) && itemId.StartsWith(CoreOrbPrefix, System.StringComparison.Ordinal);
	}

	public static string GetCoreOrbElement(string itemId)
	{
		if (!IsCoreOrb(itemId))
		{
			return string.Empty;
		}

		string rest = itemId.Substring(CoreOrbPrefix.Length); // "<element>.t<tier>"
		int marker = rest.LastIndexOf(".t", System.StringComparison.Ordinal);
		return marker > 0 ? rest.Substring(0, marker) : rest;
	}

	public static int GetCoreOrbTier(string itemId)
	{
		if (!IsCoreOrb(itemId))
		{
			return 0;
		}

		int marker = itemId.LastIndexOf(".t", System.StringComparison.Ordinal);
		if (marker < 0)
		{
			return 0;
		}

		string suffix = itemId.Substring(marker + 2);
		return int.TryParse(suffix, out int tier) ? Mathf.Clamp(tier, 1, CoreEnhanceConfig.MaxOrbTier) : 0;
	}

	// Localized "火焰核心球·T3" style name (per-element base key + tier suffix).
	public static string GetCoreOrbDisplayName(string itemId)
	{
		return $"{LocaleText.T(GetNameKey(itemId))}·T{GetCoreOrbTier(itemId)}";
	}

	private static readonly string[] CommonQuestMaterialIds =
	{
		"loot.slime_mucus",
		"loot.beast_hide",
		"loot.sharp_claw",
		"loot.soft_fur",
		"loot.small_bone",
		"loot.insect_wing",
		"loot.venom_sac",
		"loot.water_core",
		"loot.cracked_core",
	};

	public static IReadOnlyList<MonsterLootDefinition> Materials => QuestMaterials;

	public static bool IsMonsterLoot(string itemId)
	{
		if (IsCoreOrb(itemId))
		{
			return true;
		}

		foreach (MonsterLootDefinition material in QuestMaterials)
		{
			if (material.Id == itemId)
			{
				return true;
			}
		}

		return false;
	}

	public static string GetNameKey(string itemId)
	{
		if (IsCoreOrb(itemId))
		{
			return $"item.loot.core_orb.{GetCoreOrbElement(itemId)}";
		}

		foreach (MonsterLootDefinition material in QuestMaterials)
		{
			if (material.Id == itemId)
			{
				return material.NameKey;
			}
		}

		return itemId;
	}

	public static Color GetDropColor(string itemId)
	{
		if (IsCoreOrb(itemId))
		{
			return CoreOrbColors.TryGetValue(GetCoreOrbElement(itemId), out Color orbColor)
				? orbColor
				: CoreOrbColors[UniversalOrbElement];
		}

		foreach (MonsterLootDefinition material in QuestMaterials)
		{
			if (material.Id == itemId)
			{
				return material.DropColor;
			}
		}

		return new Color(0.82f, 0.92f, 1.0f, 0.95f);
	}

	public static string GetQuestItemIdForNpc(string npcDisplayName)
	{
		int index = PositiveModulo(StableStringHash(npcDisplayName), CommonQuestMaterialIds.Length);
		return CommonQuestMaterialIds[index];
	}

	public static string PickPrimaryDropForMonster(string monsterDisplayName, bool isRangedCombatant, int level)
	{
		if (monsterDisplayName.StartsWith("name.monster.", System.StringComparison.Ordinal))
		{
			return MonsterSpeciesCatalog.Current.GetPrimaryLootId(monsterDisplayName, isRangedCombatant, level);
		}

		string lowerName = monsterDisplayName.ToLowerInvariant();
		if (lowerName.Contains("slime"))
		{
			return "loot.slime_mucus";
		}

		if (lowerName.Contains("water"))
		{
			return "loot.water_core";
		}

		if (lowerName.Contains("redhorn"))
		{
			return "loot.red_horn";
		}

		if (lowerName.Contains("dragon"))
		{
			return "loot.dragon_scale";
		}

		if (lowerName.Contains("bee") || lowerName.Contains("caterpillar"))
		{
			return "loot.insect_wing";
		}

		if (lowerName.Contains("imp") || isRangedCombatant)
		{
			return "loot.venom_sac";
		}

		return level % 2 == 0 ? "loot.sharp_claw" : "loot.beast_hide";
	}

	public static string PickSecondaryDropForMonster(string primaryItemId, int level)
	{
		return primaryItemId switch
		{
			"loot.slime_mucus" => level >= 5 ? "loot.water_core" : "loot.cracked_core",
			"loot.beast_hide" => "loot.sharp_claw",
			"loot.sharp_claw" => "loot.beast_hide",
			"loot.soft_fur" => "loot.small_bone",
			"loot.small_bone" => "loot.soft_fur",
			"loot.insect_wing" => "loot.venom_sac",
			"loot.red_horn" => "loot.sharp_claw",
			"loot.venom_sac" => "loot.sharp_claw",
			"loot.water_core" => "loot.slime_mucus",
			"loot.dragon_scale" => "loot.red_horn",
			_ => "loot.cracked_core",
		};
	}

	private static int PositiveModulo(int value, int divisor)
	{
		if (divisor <= 0)
		{
			return 0;
		}

		int result = value % divisor;
		return result < 0 ? result + divisor : result;
	}

	private static int StableStringHash(string value)
	{
		unchecked
		{
			int hash = 23;
			foreach (char character in value)
			{
				hash = hash * 31 + character;
			}

			return hash;
		}
	}
}
